manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: custom-zmkfirmware
      url-base: https://github.com/ShineDoku
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: custom-zmk
      remote: custom-zmkfirmware
      revision: main
      revision: feature-test
      import: app/west.yml
  self:
    path: config
